import csv
import json
import logging
import re
from collections import defaultdict
from pathlib import Path

import requests

from ..common import (
    Icon,
    JsonValue,
    Map,
    Place,
    cached_image_url_to_dataurl,
    dump,
    format_sqm,
    get_fair_user_agent,
    get_update_date,
    identity,
    load,
    map_pairs,
)

logger = logging.getLogger(__name__)

NAME = "Jerusalem"
JSON_NAME = "jerusalem_shelters.json"
# CSV_NAME = "jerusalem_shelters.csv"

# Other possible endpoints:
#   - https://www.jerusalem.muni.il/umbraco/api/map/GetMapById
#   - https://gisviewer.jerusalem.muni.il/arcgis/rest/services
#     -> https://gisviewer.jerusalem.muni.il/arcgis/rest/services/BaseLayers/MapServer/91/query?where=1%3D1&f=pjson
# Those are point to by GIS systems available at:
#   - https://www.jerusalem.muni.il/he/residents/map/?ids=2488
#   - https://jergisng.jerusalem.muni.il/baseWab/?config=../gisviewerngsupport/api/InjectingConfig&locale=he
# The above don't seem to be as updated as the following:
#   -  https://www.jerusalem.muni.il/he/residents/security/spaces/list/
# which has the option to export as CSV:
BASE_URL_CSV = "https://www.jerusalem.muni.il/Umbraco/Surface/RecordSurface/ExportExcel"
SOURCE_URL = "https://www.jerusalem.muni.il/he/residents/security/spaces/list/"
# This is how jergisng renders shelthers:
# ICON_URL = (
#     "https://gisviewer.jerusalem.muni.il/arcgis/rest/services/BaseLayers/MapServer/91/"
#     "images/15486fa6d8662dd4170858721e70fe40"
# )
# But I prefer the residents map icon:
ICON_URL = "https://www.jerusalem.muni.il/media/s4wp3jjc/shlter_map_icon.png"
GEOCODE_SERVER_URL = "https://gisviewer.jerusalem.muni.il/arcgis/rest/services/CGC_ByNAme/GeocodeServer/"


def normalize_addr(s: str, item: dict[str, JsonValue]):
    s = re.sub(r"\s+", " ", s.strip())
    s = re.sub(r"\s+,", ",", s)
    s = s.replace("\u200b", "")
    s = s.removesuffix(", ירושלים")
    return s


class Cols:
    ID = "מספר מקלט"
    ADDR1 = "כתובות למפה"
    ADDR2 = "כתובת"
    AREA = "שטח"
    TYPE = "סוג"
    ACCESS = "נגישות"
    CAPACITY = "מס' נפשות"
    JURISDICTION = "שייכות"
    ADMINSTRATION = "מינהל"
    NEIGHBORHOOD = "שכונה"
    CATEGORY = "קטגוריה"
    LAT = "קואורדינטות ציר x"
    LON = "קורדינטות ציר y"

    # generated by the script
    SOURCE = "מקור המידע"
    RECORD_DATE = "תאריך טעינה"


DESCRIPTION_MAPPING = {
    Cols.ID: ("זיהוי", identity),
    Cols.ADDR1: ("כתובת", identity),
    Cols.ADDR2: ("כתובת נוספת", identity),
    Cols.AREA: ("שטח", format_sqm),
    Cols.TYPE: True,
    Cols.ACCESS: True,
    Cols.CAPACITY: True,
    Cols.JURISDICTION: True,
    Cols.ADMINSTRATION: True,
    Cols.NEIGHBORHOOD: True,
    Cols.CATEGORY: True,
    Cols.SOURCE: True,
    Cols.RECORD_DATE: True,
}


def geocode_addresses_batch(
    session: requests.Session,
    addrs: list[str],
    *,
    chunk_size: int = 200,
    out_sr: int = 4326,
    timeout: int = 20,
    min_score: int = 75,
) -> dict[int, tuple[float, float, int]]:
    """
    Batch geocode using CGC_ByNAme geocodeAddresses.

    Input: list of SingleLine strings (e.g. "יעל 11, ירושלים")
    Output: {input_index: (lon, lat, score)} for matches with score >= min_score

    Notes:
      - This locator expects the per-record attribute field name 'SingleLine'
        (NOT Address/City).
      - ArcGIS returns x=lon, y=lat when outSR=4326.
    """
    results: dict[str, tuple[float | None, float | None]] = {addr: (None, None) for addr in addrs}

    for start in range(0, len(addrs), chunk_size):
        chunk = addrs[start : start + chunk_size]

        records = []
        for i, s in enumerate(chunk):
            records.append(
                {
                    "attributes": {
                        # Use a stable ID so we can map results back to input
                        "OBJECTID": start + i,
                        "SingleLine": s,
                    }
                }
            )

        payload = {
            "f": "pjson",
            "outSR": out_sr,
            "addresses": json.dumps({"records": records}, ensure_ascii=False),
        }

        r = session.post(
            f"{GEOCODE_SERVER_URL}geocodeAddresses",
            data=payload,
            timeout=timeout,
        )
        r.raise_for_status()
        data = r.json()

        for locations in data.get("locations", []):
            attrs = locations.get("attributes", {})
            location = locations.get("location", {})

            idx = attrs.get("ResultID")
            if idx is None or not isinstance(idx, int) or idx < 0 or idx >= len(addrs):
                logger.warning("Server returned result with an invalid ResultID=%r", idx)
                continue

            addr = addrs[idx]

            score = int(attrs.get("Score") or locations.get("score", 0))
            if score < min_score:
                logger.warning(
                    "Skipping geocode result with score=%s < min_score=%s for addr=%r => %s",
                    score,
                    min_score,
                    addr,
                    attrs,
                )
                continue
            x = location.get("x")
            y = location.get("y")

            try:
                lon = float(x)
                lat = float(y)
            except (TypeError, ValueError):
                continue

            results[addr] = (lon, lat)

    return results


def fix_item_during_generate(item: dict):
    neighborhood = item[Cols.NEIGHBORHOOD]
    shelter_type = item[Cols.TYPE]

    categories = item[Cols.CATEGORY].split(",")
    neighborhoods = [neighborhood] if neighborhood else []
    shelter_types = {shelter_type} if shelter_type else set()
    for category in categories:
        category = category.strip()
        if "מקלט" in category or "מרחב מוגן" in category:
            shelter_types.add(category)
        else:
            neighborhoods.append(category)

    neighborhood = ", ".join(sorted(set(neighborhoods)))

    access_from_type = None
    if "מקלט" in shelter_types and any("מקלט " in s for s in shelter_types):
        shelter_types -= {"מקלט"}

    if "מקלט נגיש" in shelter_types:
        shelter_types -= {"מקלט נגיש"}
        access_from_type = "מקלט נגיש"

    if len(shelter_types) > 1:
        logger.warning("More than one shelter type: %s", shelter_types)

    access_from_record = item[Cols.ACCESS]
    if "יסודי" in access_from_record:
        shelter_type = {f"{s} {access_from_record}" if "בבית ספר" in s else s for s in shelter_types}
        access_from_record = None

    item[Cols.ACCESS] = ", ".join(sorted({x for x in (access_from_record, access_from_type) if x}))

    shelter_type = ", ".join(sorted(shelter_types))

    if "יסודי" in item[Cols.ACCESS]:
        logger.warning("Bad %s: item=%r", Cols.ACCESS, item)

    if len(shelter_types) > 1:
        logger.warning("Multiple shelter types: item", item)

    item[Cols.NEIGHBORHOOD] = neighborhood
    item[Cols.TYPE] = shelter_type
    item[Cols.CATEGORY] = None
    return item


def generate_map(data_dir: Path, icons_as_dataurls: bool = True):
    json_path = data_dir / JSON_NAME
    logger.debug("Reading: %s", json_path)

    data = load(json_path)
    update_date = get_update_date(json_path)
    logger.debug("Loaded. Update date: %s", update_date)

    places = []

    # TODO : It'd be nice to have distinct icons per shelter type,
    #        but the GIS service doesn't provide additional icons,
    #        and the "סוג" column almost never contains the actual type.
    icon_url = ICON_URL
    if icons_as_dataurls:
        icon_url = cached_image_url_to_dataurl(icon_url)
    icon = Icon(label="מקלט", url=icon_url)
    icons = [icon]

    for item in data:
        item = fix_item_during_generate(item)
        item = dict(item, **{Cols.SOURCE: SOURCE_URL, Cols.RECORD_DATE: update_date})
        name = item[Cols.ADDR1]
        shelter_type = item[Cols.TYPE]
        if shelter_type:
            name = f"{shelter_type} {name}"

        lon_str = item[Cols.LON]
        lat_str = item[Cols.LAT]

        if not lon_str or not lat_str:
            logger.warning(f"Missing coordinates for {name!r}. Skipping.")
            continue

        lon = float(lon_str)
        lat = float(lat_str)

        desc = map_pairs(item, mapping=DESCRIPTION_MAPPING)
        places.append(Place(name=name, desc=desc, icon=icon, lon=lon, lat=lat))

    logger.debug("Number of entries: %s, unique places: %s, icons: %s", len(data), len(places), len(icons))

    return Map(icons=icons, places=places)


def fix_item_during_download(item: dict[str, JsonValue]):
    addr1 = item[Cols.ADDR1] = normalize_addr(item[Cols.ADDR1], item)
    addr2 = item[Cols.ADDR2] = normalize_addr(item[Cols.ADDR2], item)
    if addr1 == addr2:
        addr2 = item[Cols.ADDR2] = None

    return item


def download_data(data_dir: Path, node_id: int = 139154, skip_geocodes: bool = False):
    session = requests.Session()
    user_agent = get_fair_user_agent()
    session.headers.update({"user-agent": user_agent})
    logger.debug("Session headers: %s", session.headers)

    params = {"nodeId": str(node_id), "culture": "he-IL", "searchMs": "true"}
    headers = {
        "content-type": "application/json; charset=UTF-8",
    }
    kwargs = dict(
        url=BASE_URL_CSV,
        params=params,
        headers=headers,
    )
    logger.debug(
        "Downloading: %s",
        kwargs,
    )
    response = session.get(**kwargs)
    response.raise_for_status()

    # strip byte-order mark if it exists
    contents = response.content.decode("utf-8")
    contents = contents.lstrip("\ufeff").splitlines()
    reader = csv.DictReader(contents)
    items = [fix_item_during_download(item) for item in reader]

    missing_lonlat_addr_to_items: dict[str, list[dict[str, JsonValue]]] = defaultdict(list)

    for item in items:
        addr = item[Cols.ADDR1]
        lon_str = item[Cols.LON]
        lat_str = item[Cols.LAT]

        if not lon_str or not lat_str:
            missing_lonlat_addr_to_items[addr].append(item)

    if not skip_geocodes:
        logger.debug("Geocoding %s addresses with missing coordinates...", len(missing_lonlat_addr_to_items))
        geocodes = geocode_addresses_batch(session, sorted(missing_lonlat_addr_to_items))
        for addr, (lon, lat) in geocodes.items():
            for item in missing_lonlat_addr_to_items[addr]:
                # only update missing fields
                item[Cols.LON] = item[Cols.LON] or lon
                item[Cols.LAT] = item[Cols.LAT] or lat

    out_path = data_dir / JSON_NAME
    dump(json.dumps(items, indent=1, ensure_ascii=False), out_path)
